### ISSUE TITLE
Request: a more darker version

### ISSUE THREAD

**Issue by enzime4u** [Monokai/monokai-pro-vscode#192] opened 2020-05-14 23:08 UTC
I like the Monokai theme a lot, it is possible to get a even dark-blue version of it ? 
Thank you

**Comment by Gameghostify** [comment] 2020-05-24 17:07
Duplicate of #180 

An even darker theme would be amazing

**Comment by barmadrid** [comment] 2020-05-31 21:12
I agree!

I like the Filter Spectrum variant the best so I spent the last few weeks developing a slightly higher contrast version based on the Filter Spectrum variant... managed to select the color shades so far!

**Comment by enzime4u** [comment] 2020-06-01 20:14
Actually I was looking for a new  Filter  from Monokai , trying to keep the synthax the same but pivoting to a more Dark Blue version of background, shadows etc ...

**Comment by Monokai** [comment] 2020-06-06 14:05
Not for now :)

**Closed by Monokai** 2020-06-06 14:05 UTC
