### ISSUE TITLE
Terminal colors don't always match their "name"

### ISSUE THREAD

**Issue by cwardzala** [Monokai/monokai-pro-vscode#196] opened 2020-05-21 15:18 UTC
It appears that colors intended to be `blue` are rendering orange? I have verified that this is unique to the terminal in VSCode. You can see my examples where color is correct using the default VSCode dark theme and incorrect using the Monokai Pro theme.

This is the correct color rendering.
![correct](https://user-images.githubusercontent.com/22216/82574048-90602680-9b54-11ea-98d6-8c7acbb8fc89.png)

This is how the Monokai Pro theme renders incorrectly in VSCode.
![incorrect](https://user-images.githubusercontent.com/22216/82573809-3d866f00-9b54-11ea-8f72-587dcf0c7001.png)

I understand that there will be differences in colors based on theme, but this is so wildly different.

**Comment by cwardzala** [comment] 2020-05-21 15:31
Here are some more comprehensive tests using this script.
```bash
curl https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash
```

VSCode Dark
![vscode_dark](https://user-images.githubusercontent.com/22216/82575490-8b9c7200-9b56-11ea-953d-da580b18d068.png)

Monokai Pro
![monokai](https://user-images.githubusercontent.com/22216/82575519-96570700-9b56-11ea-9201-e5a619553a0d.png)

**Comment by ntwb** [comment] 2020-05-22 00:23
This is by design, you can take a look at this long running discussion on the subject, possibly close this issue in favour of this one:

> https://github.com/Monokai/monokai-pro-sublime-text/issues/45

**Comment by Monokai** [comment] 2020-06-06 13:59
Correct!

**Closed by Monokai** 2020-06-06 13:59 UTC
