### ISSUE TITLE
Increase visibility of tabs

### ISSUE THREAD

**Issue by nblackburn** [Monokai/monokai-pro-vscode#10] opened 2017-08-25 11:57 UTC
At the moment the tabs are the same colour as the editor and are difficult to make out. I think the tab background should contrast against the editor background but keep the active tab the same colour so it creates a visual indicator of their existence but also the active tab.

**Comment by Monokai** [comment] 2017-08-30 15:52
This is by design. I tried to minimize visual clutter and give VSCode a clean look.

**Comment by nblackburn** [comment] 2017-08-30 15:59
I would have to disagree and think the lack of separation creates more clutter.

**Comment by Monokai** [comment] 2017-09-21 17:16
Closing it for now

**Closed by Monokai** 2017-09-21 17:16 UTC
